<?

/**
 * Implementation of hook_menu()
 */
function grabbit_tags_menu() {

  $items['tags/display'] = array( 
    'page callback' => 'grabbit_tags_display', 
    'access arguments' => array('access content')
  );

  return $items;
}

function grabbit_tags_display(){
	
	$nid=$_GET['nid'];
	$type=$_GET['type'];
	
	$node=node_load($nid);
	
	foreach($node->tags as  $tag_group){
		foreach($tag_group as $tag){
		  $text[]=$tag->name;	
		}
	}
	
	$text=implode(' ',$text);
	print $text;
	$output = '<div class="tags-engine"><span class="all-tags">';
	
	$output = '</span><span class=""></div>';
	
}