<?php

/**
 * Implementation of hook_menu()
 */
function oauth_twitter_menu()
{
  $items['confirm/twitter'] = array( 
    'title' => 'Grabbit application has been added', 
    'page callback' => 'oauth_twitter_page', 
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
 
  $items['application/twitter'] = array( 
    'title' => 'Grabbit application', 
    'page callback' => 'oauth_twitter_authorize', 
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
  return $items;
}

function oauth_twitter_page(){
	
	include 'includes/EpiCurl.php';
	include 'includes/EpiOAuth.php';
	include 'includes/EpiTwitter.php';
	include 'includes/secret.php';
	
	$twitterObj = new EpiTwitter($consumer_key, $consumer_secret);

	$twitterObj->setToken($_GET['oauth_token']);
	$token = $twitterObj->getAccessToken();
	$twitterObj->setToken($token->oauth_token, $token->oauth_token_secret);
	$twitterInfo= $twitterObj->get_accountVerify_credentials();
	$twitterInfo->response;
	$output = "Your twitter username is {$twitterInfo->screen_name} and your profile picture is <img src=\"{$twitterInfo->profile_image_url}\">";
	$tok = file_put_contents('tok', $token->oauth_token);
	$sec = file_put_contents('sec', $token->oauth_token_secret);
	print_r($tok);
	return $output;
}

function oauth_twitter_authorize(){
	include 'includes/EpiCurl.php';
	include 'includes/EpiOAuth.php';
	include 'includes/EpiTwitter.php';
	include 'includes/secret.php';

	$twitterObj = new EpiTwitter($consumer_key, $consumer_secret);

	echo '<a href="' . $twitterObj->getAuthorizationUrl() . '">Authorize with Twitter</a>';
}