<?

/**
 * Implementation of hook_menu()
 */
function grabbit_realtime_menu() {

  $items['execute/realtime'] = array( 
    'page callback' => 'grabbit_realtime_perform', 
    'access arguments' => array('access content')
  );

  return $items;
}

function grabbit_realtime_perform(){
	$user = $_GET['user'];
	$pannel = $_GET['pannel'];
	
	print $user . " - " . $pannel;
}

//hook grabbit_status_form
function grabbit_realtime_grabbit_status_form(){
	drupal_add_js(drupal_get_path('module', 'grabbit_realtime').'/real_engine.js', $type = 'module');
	
}