<?

/**
 * Implementation of hook_menu()
 */
function grabbit_me_menu() {

  $items['albums/calculate'] = array( 
    'page callback' => 'grabbit_albums_calculate', 
    'access arguments' => array('access content')
  );

  $items['albums/display'] = array( 
    'page callback' => 'grabbit_albums_display', 
    'title' => 'album',
    'access arguments' => array('access content')
  );

  return $items;
}

function grabbit_albums_preprocess_node(&$variables){
	print_r($variables);
}

function grabbit_albums_display(){
	drupal_add_js(drupal_get_path('module', 'facebook_grabbit').'/facebook_grabbit.js', $type = 'module');
}

function grabbit_albums_calculate(){
	
}