<?

/**
 * Implementation of hook_menu()
 */
function grabbit_albums_menu() {

  $items['albums/calculate'] = array( 
    'page callback' => 'grabbit_albums_calculate', 
    'access arguments' => array('access content')
  );

  $items['albums/display'] = array( 
    'page callback' => 'grabbit_albums_display', 
    'title' => 'album',
    'access arguments' => array('access content')
  );

  return $items;
}

function grabbit_albums_preprocess_node(&$variables){
	print_r($variables);
	if($variables->type=='media'){
		global $user;
		drupal_add_js(drupal_get_path('module', 'grabbit_albums').'/albums_engine.js', $type = 'module');
		
		$controls = grabbit_aldums_calculate_next($variables->field_media_type[0]['value'],$user,$variables->nid);
		
	}
}

function grabbit_aldums_calculate_next($type,$user,$nid){
	
	switch($type){
		case "mov":
		case "mp3":
		case "flv":
		// media
		  $types = array('mov','mp3','flv');  
		break;
		case "doc":
		case "rtf":
		case "txt":
		case "csv":
		case "ppt":
		case "xls":
		case "pdf":
		// documents
		  $types = array('doc','rtf','txt','csv','ppt','xls','pdf');  
		break;
		default:
		// photos
		  $types = array('jpeg', 'bmp', 'jpg', 'png', 'gif');
		break;
	}
	print_r($types);
	$sql_more="SELECT node.nid AS nid
	 FROM node node 
	 LEFT JOIN content_type_media node_data_field_media_type ON node.vid = node_data_field_media_type.vid
	 INNER JOIN users users ON node.uid = users.uid
	 WHERE (node.type in (%s)) AND ((node_data_field_media_type.field_media_type_value) in (".implode($types,',').")) AND (users.uid in (%d)) AND (node.nid > %d) LIMIT 1";
	
	$more = db_result(db_query($sql_more,'media',$user->uid,$nid));
	
	print_r($more);
}

function grabbit_albums_display(){
	drupal_add_js(drupal_get_path('module', 'facebook_grabbit').'/facebook_grabbit.js', $type = 'module');
}

function grabbit_albums_calculate(){
	
}