<?
// CUSTOM TAGS API
function grabbit_customtags_add_to_queue($uid,$id,$type,$tags){
	db_query("INSERT INTO {grabbit_customtags} SET uid=%d, type='%s', id='%s', tags='%d",$uid,$type,$id,$tags);
}

//check for specific item in queue (only facebook and twitter) returns the tags
function grabbit_customtags_check_queue($uid,$id,$type){
	$tags = db_query("SELECT tags, faid FROM {grabbit_customtags} WHERE uid=%d, type='%s', id='%s'",$uid,$type,$id);
	if(!db_affected_rows($tags)){
	  return;
	}
	
	$totals=db_fetch_object($tags);
	db_query("DELETE FROM {grabbit_customtags} WHERE faid=%d",$totals->faid);
	return $totals->tags;
}