<?php

/**
 * Implementation of hook_menu_alter
 * reorders tabs and menus throughout grabbit
 */
function grabbit_tabs_menu_alter( &$items )
{
  //print_r($items);
  $items['user/%/myfriends']['type'] = MENU_CALLBACK;
  $items['user/%user/invites']['type'] = MENU_CALLBACK;
  $items['user/%user/contact']['type'] = MENU_CALLBACK;
  $items['user/%user/track/navigation']['type'] = MENU_CALLBACK;
  $items['user/%user/edit']['type'] = MENU_CALLBACK;
print_r($items);
}