<?php

/**
 * Implementation of hook_block()
 */
function friend_search_block($op = 'list', $delta = 0, $edit = array()) {
  switch($op) {
    case 'list':
      $blocks[0]['info'] = t('Friend Search');
      return $blocks;
      break;
    case 'view':
      switch ( $delta )
      {
		case 0:
          $blocks['title'] = 'Find People';
          $blocks['content'] = drupal_get_form('friend_search_people_form');
          break;
      }
      return $blocks;
      break;
  }
}

/**
 * Implementation of hook_menu()
 */
function friend_search_menu()
{
  $items['user/search'] = array( 
    'title' => 'Find People', 
    'page callback' => 'friend_search_page', 
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  ); 
  return $items;
}

/**
 * Retrieves and displays page view
 */
function friend_search_page()
{
  $view = views_get_view('friend_search');
  $display_id = 'page';
  $view->set_display($display_id);
  $view->is_cacheable = FALSE;
  
  print_r($_GET);
  if ($_GET['username'])
  {
    $item = $view->get_item($display_id, 'filter', 'title');
    $item['value'] = $_GET['username'];
    unset($_GET['username']);
    
    $view->set_item($display_id, 'filter', 'title', $item);
  }
  
  return $view->render();
}

/**
 * Implementation of hook_form() for find people
 */
function friend_search_people_form($form_state){
	
  	$form['username'] = array(
	    '#type' => 'textfield',
	    '#size' => 60,
	    '#maxlength' => 255,
	    '#required' => true );

	$form['submit'] = array(
	    '#type' => 'submit',
	    '#value' => t('Search'),
	    '#weight'=>10
	);	
	
	$form['#action'] = url('user/search');
	
	$form['#method'] = 'get';
	
  return $form;
}
