<?php

/**
 * Implementation of hook_block()
 */
function friend_search_block($op = 'list', $delta = 0, $edit = array()) {
  switch($op) {
    case 'list':
      $blocks[0]['info'] = t('Friend Search');
      $blocks[1]['info'] = t('Search Content');
      $blocks[2]['info'] = t('Status Form');
      return $blocks;
      break;
    case 'view':
      switch ( $delta )
      {
		case 0:
          $blocks['title'] = 'Are this people yor friends?';
//          $blocks['content'] = drupal_get_form('friend_search_people_form');

          break;
		case 1:
          $blocks['title'] = 'Search Content';
//          $blocks['content'] = drupal_get_form('search_form');
          $blocks['content']= friend_search_are_friends();
          break;
		case 2:
         // $blocks['content'] = '<div class="panels-update-form">
		 //            <div class="panels-update-wraper">'.drupal_get_form('facebook_grabbit_update_form').'</div>
		  //         </div>';
		          $blocks['content']= friend_search_are_friends();
          break;
      }
      return $blocks;
      break;
  }
}

function friend_search_are_friends(){
	    include("facebook/config.php");
	
		$fuser = facebook_grabbit_get_fid(1);
		$suser=$fuser->fid;
		$session_key=$fuser->kid;
		
		$facebook = new FacebookDesktop($api_key, $secret);
		$facebook->set_user($suser, $session_key);
		
		$status = $facebook->api_client->call_method("Friends.areFriends", array('uids1'=>$fuser->fid, 'uids2'=>'862760330'));
		print_r($status);

}


/**
 * Implementation of hook_views_pre_view()
 */
function friend_search_views_pre_render(&$view){


	
}

/**
 * Implementation of hook_menu()
 */
function friend_search_menu()
{
  $items['user/search'] = array( 
    'title' => 'Find People', 
    'page callback' => 'friend_search_page', 
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  ); 
  return $items;
}

/**
 * Retrieves and displays page view
 */
function friend_search_page()
{
  $view = views_get_view('friend_search');
  
  $view->use_ajax = TRUE;
  $display_id = 'default';
  $view->set_display($display_id);
  $view->is_cacheable = FALSE;
  
  if ($_GET['username'])
  {
    $item = $view->get_item($display_id, 'filter', 'title');
    $item['value'] = $_GET['username'];
    unset($_GET['username']);
    
    $view->set_item($display_id, 'filter', 'title', $item);
  }
  
  return $view->render();
}

/**
 * Implementation of hook_form() for find people
 */
function friend_search_people_form($form_state){
	
  	$form['username'] = array(
	    '#type' => 'textfield',
	    '#size' => 60,
	    '#maxlength' => 255,
	    '#required' => true );

	$form['submit'] = array(
	    '#type' => 'submit',
	    '#value' => t('Search'),
	    '#weight'=>10
	);	
	
	$form['#action'] = url('user/search');
	
	$form['#method'] = 'get';
	
  return $form;
}

/**
 * Implementation of hook_menu_alter() to customize search
 */
function friend_search_menu_alter(&$items) {
    unset($items['search/user/%menu_tail']); // So the Tab "Users" doesnt appear in the search page
}
