<?php

/**
 * Implementation of hook_block()
 */
function friend_search_block($op = 'list', $delta = 0, $edit = array()) {
  switch($op) {
    case 'list':
      $blocks[0]['info'] = t('Friend Search');
      $blocks[1]['info'] = t('Search Content');
      $blocks[2]['info'] = t('Status Form');
      return $blocks;
      break;
    case 'view':
      switch ( $delta )
      {
		case 0:
          $blocks['title'] = 'Are this people yor friends?';
          $blocks['content'] = drupal_get_form('friend_search_people_form');

          break;
		case 1:
          $blocks['title'] = 'Search Content';
          $blocks['content'] = drupal_get_form('search_form');
          	
          break;
		case 2:
          $blocks['content'] = '<div class="panels-update-form">
		             <div class="panels-update-wraper">'.drupal_get_form('facebook_grabbit_update_form');
		
          $blocks['content'] .= '<div class="upload_button_expand"><a href="#">&raquo; Upload file</a></div>
                                 <div class="panels-update-form_file" style="display:none">
                                 <div id="swfupload-control">  
							       <p>Select an image file (jpg, png, gif) or video (mov, flv) having maximum size of 1MB</p>  
							       <input type="button" id="button" />  
							       <p id="queuestatus" ></p>  
							       <ol id="log"></ol>  
							     </div>
				               </div></div>
       		           </div>';	
		
          break;
      }
      return $blocks;
      break;
  }
}


/**
 * Implementation of hook_menu()
 */
function friend_search_menu()
{
  $items['user/search'] = array( 
    'title' => 'Find People', 
    'page callback' => 'friend_search_page', 
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  ); 

  $items['user/%/myfriends'] = array( 
    'title' => 'Friends', 
    'page callback' => 'friend_search_show_friends', 
 	'page arguments' => array(1),
    'load arguments' => array('%map', '%index'),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK
  );

  $items['user/%/myfriends/facebook_friends'] = array(
   'title' => 'Facebook Friends',
   'page callback' => 'friend_search_show_friends_facebook',
   'access arguments' => array('access content'),
   	'page arguments' => array(1),
    'load arguments' => array('%map', '%index'),
   'weight' => 9,
   'type' => MENU_LOCAL_TASK,
  );

  $items['user/%/myfriends/twitter_friends'] = array(
   	'title' => 'Twitter Friends',
  	'page callback' => 'friend_search_show_friends_twitter',
	   'access arguments' => array('access content'),
	   	'page arguments' => array(1),
	    'load arguments' => array('%map', '%index'),
	   'weight' => 9,
	   'type' => MENU_LOCAL_TASK,
	  );

  $items['user/%/myfriends/viewfriends'] = array(
    'title' => 'Grabbit Friends',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'load arguments' => array('%map', '%index'),
  );
  

  return $items;
}

function friend_search_show_friends_facebook(){
	global $user;
	
	drupal_add_js(drupal_get_path('module', 'friend_search').'/engine.js', $type = 'module');

	$fuser = facebook_grabbit_get_fid($user->uid);
	$profile = content_profile_load('profile', $user->uid);
	
	if ($fuser){
		
	  include_once("facebook/facebook.php");
	  include_once("facebook/facebook_desktop.php");
	  include_once("facebook/config.php");

	  $suser=$fuser->fid;
	  $session_key=$fuser->kid;
      try{
	
	    $facebook = new FacebookDesktop($api_key, $secret);
	
	    if ($facebook->set_user($suser, $session_key) != null){
		  drupal_set_message("Facebook connection failed","error");
	    }
	    else{
		 
	      $friends =  $facebook->api_client->call_method('Friends.get', array('api_key' => $api_key,
									       'uid'=>"$suser")); 
		
		  $uids = implode(", ",$friends);						
		  $details = $facebook->api_client->call_method('Users.getInfo', array('api_key' => $api_key,
																       'uids'=>$uids,
																        'fields'=>'last_name, first_name, pic_small'));
		$rowx='odd';	
		foreach($details as $amigo_facebook){
			$facebooks .='<div class="facebook-friend '.$rowx.'">
			               <div class="picture"><img src="'.$amigo_facebook['pic_small'].'" /></div>
			               <div class="name">'.$amigo_facebook['first_name'].' '.$amigo_facebook['last_name'].'</div>
			             </div>';
						if($rowx=='even'){
							$rowx='odd';
						}else{
							$rowx='even';
						}
		}
									
	    $output .='<div class="facebook-list"><h2>Facebook Friends</h2><div class="facebook-container">'.$facebooks.'</div></div>';
	  }
	}catch(FacebookRestClientException $e){
		$output .='<div class="facebook-list"><h2>Facebook Friends</h2><div class="facebook-container">You have no FB account yet</div></div>';
		
	}
    }

	
	return $output;

	
}

function friend_search_show_friends_twitter(){
    global $user;
    $accounts = oauth_twitter_get_uid($user->uid);

	if($accounts){
		include_once 'includes/EpiCurl.php';
		include_once 'includes/EpiOAuth.php';
		include_once 'includes/EpiTwitter.php';
		include 'includes/secret.php';

		try{
        	$twitterObj = new EpiTwitter($consumer_key, $consumer_secret);
			$twitter_account = oauth_twitter_get_uid($user->uid);
			$token = unserialize($twitter_account->config);
			$twitterObj->setToken($token['token'], $token['secret']);
			 $twitterInfo2= $twitterObj->get_accountVerify_credentials();  
			 $twit_id = $twitterInfo2->screen_name;
			
			$requ = drupal_http_request('http://twitter.com/statuses/friends.json?screen_name='.$twit_id, $headers = array(), $method = 'GET', $data = NULL, $retry = 3);
			$unser = json_decode($requ->data);
			$rowx="odd";
			foreach($unser as $twitter){
				$twitters .='<div class="twitter-friend '.$rowx.'">
				               <div class="picture"><img width="48px" src="'.$twitter->profile_image_url.'" /></div>
				               <div class="name">'.$twitter->name.'</div>
				             </div>';
				
						if($rowx=='even'){
							$rowx='odd';
						}else{
							$rowx='even';
						}
			  
			}
	     }
	     catch(EpiOAuthBadRequestException $e){  
	        drupal_set_message("Connection error Twitter","error");
	     }catch(EpiOAuthUnauthorizedException $e){  
	        drupal_set_message("Error in Twitter","error");
	     }catch(EpiOAuthException $e){  
	        drupal_set_message("Ooops! some strange error with twitter, maybe fail wale!","error");
	     }
	
	  $output .='<div class="twitter-list"><h2>Twitter Following</h2><div class="twitter-container">'.$twitters.'</div></div>';	
	}
	
	return $output;
	
}

function friend_search_show_friends(){
	
	global $user;
	
	drupal_add_js(drupal_get_path('module', 'friend_search').'/engine.js', $type = 'module');
	
	$view = views_get_view('friends');
    $display_id = 'page_1';
    $view->set_display($display_id);	

    $output ='<div class="grabbit-list"><h2>Grabbit Friends</h2><div class="grabbit-container">'.$view->render().'</div></div>';

	
	return $output;
}

/**
 * Retrieves and displays page view
 */
function friend_search_page()
{
  $view = views_get_view('friend_search');
  
  $view->use_ajax = TRUE;
  $display_id = 'default';
  $view->set_display($display_id);
  $view->is_cacheable = FALSE;
  
  if ($_GET['username'])
  {
    $item = $view->get_item($display_id, 'filter', 'title');
    $item['value'] = $_GET['username'];
    unset($_GET['username']);
    
    $view->set_item($display_id, 'filter', 'title', $item);
  }
  
  return $view->render();
}

/**
 * Implementation of hook_form() for find people
 */
function friend_search_people_form($form_state){
	
  	$form['username'] = array(
	    '#type' => 'textfield',
	    '#size' => 60,
	    '#maxlength' => 255,
	    '#required' => true );

	$form['submit'] = array(
	    '#type' => 'submit',
	    '#value' => t('Search'),
	    '#weight'=>10
	);	
	
	$form['#action'] = url('user/search');
	
	$form['#method'] = 'get';
	
  return $form;
}

/**
 * Implementation of hook_menu_alter() to customize search
 */
function friend_search_menu_alter(&$items) {
    unset($items['search/user/%menu_tail']); // So the Tab "Users" doesnt appear in the search page
}
