<?

/**
 * Implementation of hook_menu()
 */
function grabbit_invites_menu()
{
  $items['grabbit/invite/twitter'] = array( 
    'title' => 'Invite Twitter', 
    'page callback' => 'grabbit_invites_twitter', 
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  ); 

  $items['grabbit/invite/facebook'] = array( 
    'title' => 'Invite Facebook', 
    'page callback' => 'grabbit_invites_facebook', 
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

 return $items;

}

function grabbit_invites_twitter(){
	
	global $user;
    $accounts = oauth_twitter_get_uid($user->uid);

	if($accounts){
		$module_name='oauth_twitter';
		include_once drupal_get_path('module', $module_name).'/includes/EpiCurl.php';
		include_once drupal_get_path('module', $module_name).'/includes/EpiOAuth.php';
		include_once drupal_get_path('module', $module_name).'/includes/EpiTwitter.php';
		include drupal_get_path('module', $module_name).'/includes/secret.php';
		
		 $twitterObj = new EpiTwitter($consumer_key, $consumer_secret);
		$token = unserialize($accounts->config);
		  $twitterObj->setToken($token['token'], $token['secret']);
		  $userInfo = $twitterObj->post_direct_messagesNew('14914572','testing this stuff');
		print_r($userInfo);
		
		$id=arg(3);

		if($id){

		}
	
	}
	
}

function grabbit_invites_facebook(){
	$id=arg(3);
	
	if($id){
		
		print "Invite using direct message";
		
	}
	
}