<?

/**
 * Implementation of hook_menu()
 */
function grabbit_invites_menu()
{
  $items['grabbit/invite/twitter'] = array( 
    'title' => 'Invite Twitter', 
    'page callback' => 'grabbit_invites_twitter', 
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  ); 

  $items['grabbit/invite/facebook'] = array( 
    'title' => 'Invite Facebook', 
    'page callback' => 'grabbit_invites_facebook', 
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

 return $items;

}

function grabbit_invites_twitter(){
	
	global $user;
    $accounts = oauth_twitter_get_uid($user->uid);

	if($accounts){
		$id=arg(3);

		if($id){
			
				$module_name='oauth_twitter';
				include_once drupal_get_path('module', $module_name).'/includes/EpiCurl.php';
				include_once drupal_get_path('module', $module_name).'/includes/EpiOAuth.php';
				include_once drupal_get_path('module', $module_name).'/includes/EpiTwitter.php';
				include drupal_get_path('module', $module_name).'/includes/secret.php';

				$twitterObj = new EpiTwitter($consumer_key, $consumer_secret);
				$token = unserialize($accounts->config);
				$twitterObj->setToken($token['token'], $token['secret']);

			//	$twitterObj->post_statusesUpdate(array('status' =>'D '.$id.' this is a direct message from grabbit'));

		}
	
	}
	
}

function grabbit_invites_facebook(){
	
	global $user;
	
	$fuser = facebook_grabbit_get_fid($user->uid);
	
	if ($fuser){
	  $module_name='facebook_grabbit';
	  require_once(drupal_get_path('module', $module_name)."/facebook/facebook.php");
	  require_once(drupal_get_path('module', $module_name)."/facebook/facebook_desktop.php");
	  include(drupal_get_path('module', $module_name)."/facebook/config.php");

	  $suser=$fuser->fid;
	  $session_key=$fuser->kid;
      try{
	
	    $facebook = new FacebookDesktop($api_key, $secret);
	
	    if ($facebook->set_user($suser, $session_key) != null){
		  drupal_set_message("Facebook connection failed","error");
	    }
	    else{
		 
	     $testing = $facebook->api_client->call_method('facebook.notifications.send', array('api_key' => $api_key,
									       'to_ids'=>array('100000114639239'),
									       'notification'=>'probando en el facebook')); 
									
	    }
	  }catch(FacebookRestClientException $e){
		
	  }
    }
	
	$id=arg(3);
	
	if($id){
		
		print "Invite using direct message";
		
	}
	
}